import { z } from 'zod';

export const ERROR_CODES = {
  MATCH_FULL: 'MATCH_FULL',
  ALREADY_JOINED: 'ALREADY_JOINED',
  NOT_PARTICIPANT: 'NOT_PARTICIPANT',
  OVERLAPPING_MATCH: 'OVERLAPPING_MATCH',
  REQUIREMENTS_NOT_MET: 'REQUIREMENTS_NOT_MET',
  INVITATION_REQUIRED: 'INVITATION_REQUIRED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_CONSUMED: 'INVITATION_CONSUMED',
  RATING_WINDOW_CLOSED: 'RATING_WINDOW_CLOSED',
  ATTENDANCE_WINDOW_CLOSED: 'ATTENDANCE_WINDOW_CLOSED',
  DISPUTE_WINDOW_CLOSED: 'DISPUTE_WINDOW_CLOSED',
  DISPUTE_ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  USERNAME_CHANGE_TOO_SOON: 'USERNAME_CHANGE_TOO_SOON',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_BANNED: 'USER_BANNED',
  SELF_RATING_FORBIDDEN: 'SELF_RATING_FORBIDDEN',
  DUPLICATE_RATING: 'DUPLICATE_RATING',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const errorCodeValues = Object.values(ERROR_CODES) as [ErrorCode, ...ErrorCode[]];
export const ErrorCodeSchema = z.enum(errorCodeValues);
export const ApiErrorSchema = z.object({
  code: ErrorCodeSchema,
  message: z.string(),
  details: z.unknown().optional(),
  requestId: z.string().optional(),
});
export type ApiError = z.infer<typeof ApiErrorSchema>;
